#pragma once

#define NAMEPACE_STARREALM            ::starrealm

#define STARREALM_ENTITY              NAMEPACE_STARREALM::entity

#define STARREALM_ENTITY_STARSTYLE    STARREALM_ENTITY::star_style
#define STARREALM_ENTITY_FILL         STARREALM_ENTITY_STARSTYLE::fill
#define STARREALM_ENTITY_COLOR        STARREALM_ENTITY_STARSTYLE::color
